package space.cougs.ground.utils;

public enum CISErrors {
  SUCCESS,
  INVALID_ARGS,
  OUT_OF_MEMORY,
  CRC,
  FILE_NOT_FOUND,
  WRITE_PROTECTION,
  EOF,
  NOT_SUPPORTED,
  BUFFER_OVERFLOW,
  INVALID_PASSWORD,
  WRITE,
  READ,
  NACK,
  OPEN_FAILED,
  DISK_FULL,
  BUSY,
  ALREADY_EXIST,
  QUEUE_OVERFLOW,
  WAIT_TIMEOUT,
  WATCHDOG,
  INVALID_ADDRESS,
  POWER_LIMITED,
  POWER_EMERGENCY,
  COMMS_INTERRUPTED,
  UNKNOWN_COMMAND
}
