.TH "Comms" 3 "Fri Mar 6 2020" "Version 0.0.1" "CougSat1-IHU" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Comms
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBSubsystem\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBComms\fP (const \fBComms\fP &)=delete"
.br
.ti -1c
.RI "\fBComms\fP & \fBoperator=\fP (const \fBComms\fP &)=delete"
.br
.ti -1c
.RI "\fBComms\fP (SPI &spi)"
.br
.RI "Construct a new Comms::Comms object\&. "
.ti -1c
.RI "\fB~Comms\fP ()"
.br
.RI "Destroy the Comms::Comms object\&. "
.ti -1c
.RI "mbed_error_status_t \fBinitialize\fP ()"
.br
.RI "Initialize the \fBComms\fP\&. "
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Comms::Comms (SPI & spi)"

.PP
Construct a new Comms::Comms object\&. 
.PP
\fBParameters:\fP
.RS 4
\fIspi\fP connected to the \fBComms\fP 
.RE
.PP

.SS "Comms::~Comms ()"

.PP
Destroy the Comms::Comms object\&. 
.SH "Member Function Documentation"
.PP 
.SS "mbed_error_status_t Comms::initialize ()\fC [virtual]\fP"

.PP
Initialize the \fBComms\fP\&. 
.PP
\fBReturns:\fP
.RS 4
mbed_error_status_t 
.RE
.PP

.PP
Implements \fBSubsystem\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for CougSat1-IHU from the source code\&.
