.TH "IFJR" 3 "Fri Mar 6 2020" "Version 0.0.1" "CougSat1-IHU" \" -*- nroff -*-
.ad l
.nh
.SH NAME
IFJR
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBSubsystem\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBIFJR\fP (const \fBIFJR\fP &)=delete"
.br
.ti -1c
.RI "\fBIFJR\fP & \fBoperator=\fP (const \fBIFJR\fP &)=delete"
.br
.ti -1c
.RI "\fBIFJR\fP (I2C &i2c)"
.br
.RI "Construct a new IFJR::IFJR object\&. "
.ti -1c
.RI "\fB~IFJR\fP ()"
.br
.RI "Destroy the IFJR::IFJR object\&. "
.ti -1c
.RI "mbed_error_status_t \fBinitialize\fP ()"
.br
.RI "Initialize the \fBIFJR\fP\&. "
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "IFJR::IFJR (I2C & i2c)"

.PP
Construct a new IFJR::IFJR object\&. 
.PP
\fBParameters:\fP
.RS 4
\fIi2c\fP connected to the \fBIFJR\fP 
.RE
.PP

.SS "IFJR::~IFJR ()"

.PP
Destroy the IFJR::IFJR object\&. 
.SH "Member Function Documentation"
.PP 
.SS "mbed_error_status_t IFJR::initialize ()\fC [virtual]\fP"

.PP
Initialize the \fBIFJR\fP\&. 
.PP
\fBReturns:\fP
.RS 4
mbed_error_status_t 
.RE
.PP

.PP
Implements \fBSubsystem\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for CougSat1-IHU from the source code\&.
