.TH "PMIC" 3 "Fri Mar 6 2020" "Version 0.0.1" "CougSat1-IHU" \" -*- nroff -*-
.ad l
.nh
.SH NAME
PMIC
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBSubsystem\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBPMIC\fP (const \fBPMIC\fP &)=delete"
.br
.ti -1c
.RI "\fBPMIC\fP & \fBoperator=\fP (const \fBPMIC\fP &)=delete"
.br
.ti -1c
.RI "\fBPMIC\fP (I2C &i2c)"
.br
.RI "Construct a new PMIC::PMIC object\&. "
.ti -1c
.RI "\fB~PMIC\fP ()"
.br
.RI "Destroy the PMIC::PMIC object\&. "
.ti -1c
.RI "mbed_error_status_t \fBinitialize\fP ()"
.br
.RI "Initialize the \fBPMIC\fP\&. "
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "PMIC::PMIC (I2C & i2c)"

.PP
Construct a new PMIC::PMIC object\&. 
.PP
\fBParameters:\fP
.RS 4
\fIi2c\fP connected to the \fBPMIC\fP 
.RE
.PP

.SS "PMIC::~PMIC ()"

.PP
Destroy the PMIC::PMIC object\&. 
.SH "Member Function Documentation"
.PP 
.SS "mbed_error_status_t PMIC::initialize ()\fC [virtual]\fP"

.PP
Initialize the \fBPMIC\fP\&. 
.PP
\fBReturns:\fP
.RS 4
mbed_error_status_t 
.RE
.PP

.PP
Implements \fBSubsystem\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for CougSat1-IHU from the source code\&.
